// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1N8h930iA6MNzn74fA8JsYeuXXM4yfxA',
    appId: '1:729857533116:web:ca667bb5d2dad97aefdcb9',
    messagingSenderId: '729857533116',
    projectId: 'fir-tutorial-1874a',
    authDomain: 'fir-tutorial-1874a.firebaseapp.com',
    storageBucket: 'fir-tutorial-1874a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASuJo1cA64HCHfAMBfIc4YPkAjoSEDCkY',
    appId: '1:729857533116:android:b683e77836b8e599efdcb9',
    messagingSenderId: '729857533116',
    projectId: 'fir-tutorial-1874a',
    storageBucket: 'fir-tutorial-1874a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlnawzksQJ-hi587NOMAxBwDzqzHoRJhw',
    appId: '1:729857533116:ios:b6c2d8d26477b022efdcb9',
    messagingSenderId: '729857533116',
    projectId: 'fir-tutorial-1874a',
    storageBucket: 'fir-tutorial-1874a.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlnawzksQJ-hi587NOMAxBwDzqzHoRJhw',
    appId: '1:729857533116:ios:b6c2d8d26477b022efdcb9',
    messagingSenderId: '729857533116',
    projectId: 'fir-tutorial-1874a',
    storageBucket: 'fir-tutorial-1874a.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
}
